# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.scritchy.org
title: Dana Cleveland - ScritchyLabs
email: dana@scritchy.org
author: Dana Cleveland
description: > # "Person website and landing page of Dana Cleveland.
  Contains information of a 25+ year polygot developer and SysAdmin. 
  Well versed on DevOps, agile, Cloud programming and day 2 management. 
copyright: 'Copyright &copy; 2018 Dana Cleveland/ScritcyLabs. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ultimav
  - title: github
    url: https://github.com/ultimav
  - title: linkedin
    url: https://www.linkedin.com/in/danacleveland
  - title: resume
    url: https://www.visualcv.com/dana-cleveland
  - title: photography
    url: https://scritchylabsphotos.pixiset.com
